// scripts/seed.js — Insère les produits depuis products.js dans MongoDB
require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const Product  = require("../src/models/Product");

// Import des données produits (copie du front)
const products = [
  { id:1, slug:"serum-eclat-ebene", name:"Sérum Éclat Ébène", category:"Soins visage", categorySlug:"soins-visage", concern:"Éclat, hydratation et confort", description:"Un sérum doux pensé pour illuminer les peaux foncées sans effet grisâtre.", price:34.9, accent:"#F0BA87", image:"/images/products/serum-eclat-ebene-card.png", badge:"Best-seller", rating:4.8, reviewCount:214, isFeatured:true, ingredients:["Vitamine C","Niacinamide","Acide hyaluronique"] },
  { id:2, slug:"gel-matifiant-sebum-control", name:"Gel Matifiant Sébum Control", category:"Soins visage", categorySlug:"soins-visage", concern:"Brillance et excès de sébum", description:"Un soin quotidien pour réguler la brillance sans assécher.", price:29.9, accent:"#601521", image:"/images/products/gel-matifiant-sebum-control-card.png", badge:"Nouveau", rating:4.6, reviewCount:98, isFeatured:false, ingredients:["Niacinamide 10%","Zinc PCA","Thé vert"] },
  { id:3, slug:"creme-apaisante-sensitive-melanin", name:"Crème Sensitive Melanin", category:"Soins visage", categorySlug:"soins-visage", concern:"Rougeurs et inconfort", description:"Une crème enveloppante pour les peaux sensibles mélaninées.", price:32.5, accent:"#D96B8A", image:"/images/products/creme-sensitive-melanin-card.png", rating:4.7, reviewCount:156, ingredients:["Centella asiatica","Céramides","Panthénol"] },
  { id:4, slug:"brume-hydra-glow", name:"Brume Hydra Glow", category:"Soins visage", categorySlug:"soins-visage", concern:"Hydratation express", description:"Une brume légère qui hydrate et illumine.", price:22.9, accent:"#C9825D", image:"/images/products/brume-hydra-glow.png", badge:"Nouveau", rating:4.7, reviewCount:83, ingredients:["Fleur d'oranger","Aloe vera","Glycérine"] },
  { id:5, slug:"tonique-aha-bha", name:"Tonique AHA/BHA Éclat & Lissant", category:"Soins visage", categorySlug:"soins-visage", concern:"Grain de peau irrégulier", description:"Un tonique exfoliant qui ravive l'éclat et désincruste les pores.", price:28.9, accent:"#7A2433", image:"/images/products/tonique-aha-bha.png", rating:4.7, reviewCount:134, ingredients:["AHA 5%","BHA 2%","Thé vert"] },
  { id:6, slug:"masque-purifiant-argile-glow", name:"Masque Purifiant Argile & Glow", category:"Soins visage", categorySlug:"soins-visage", concern:"Pores bouchés et teint terne", description:"Un masque kaolin et charbon actif qui purifie et booste l'éclat.", price:26.9, accent:"#2c2c2c", image:"/images/products/masque-purifiant.png", rating:4.6, reviewCount:91, ingredients:["Kaolin","Charbon actif","Niacinamide"] },
  { id:7, slug:"contour-yeux-eclat-nuit", name:"Contour Yeux Éclat Nuit", category:"Soins visage", categorySlug:"soins-visage", concern:"Cernes et regard fatigué", description:"Réduit les cernes, illumine et hydrate pendant la nuit.", price:38.9, accent:"#7A4A1E", image:"/images/products/contour-yeux-eclat-nuit.png", badge:"Exclusif", rating:4.8, reviewCount:112, ingredients:["Caféine","Acide hyaluronique","Rétinol 0,1%"] },
  { id:8, slug:"creme-solaire-eclat-protect-spf50", name:"Crème Solaire Éclat Protect SPF 50+", category:"Protection solaire", categorySlug:"protection-solaire", concern:"Protection UVA/UVB et prévention des taches", description:"SPF 50+ fini invisible, non comédogène, sans parfum.", price:27.9, accent:"#C9825D", image:"/images/products/creme-solaire.png", badge:"Indispensable", rating:4.8, reviewCount:178, ingredients:["Niacinamide","Vitamine E","Filtres solaires"] },
  { id:9, slug:"spf-50-tres-haute-protection", name:"SPF 50+ Très Haute Protection", category:"Protection solaire", categorySlug:"protection-solaire", concern:"Protection maximale visage & corps", description:"Bouclier solaire haute protection formule respirante.", price:24.9, accent:"#7A4A1E", image:"/images/products/spf-50.png", rating:4.7, reviewCount:96, ingredients:["Niacinamide","Vitamine E","Baobab"] },
  { id:10, slug:"huile-corps-nude-glow", name:"Huile Corps Nude Glow", category:"Corps", categorySlug:"corps", concern:"Nutrition et glow satiné", description:"Huile sèche soyeuse qui sublime les carnations foncées.", price:27.9, accent:"#F0BA87", image:"/images/products/huile-eclat-corps.png", badge:"Coup de cœur", rating:4.9, reviewCount:187, ingredients:["Huiles précieuses","Vitamine E"] },
  { id:11, slug:"beurre-karite-baobab", name:"Beurre Corps Karité & Baobab", category:"Corps", categorySlug:"corps", concern:"Nutrition profonde", description:"Beurre onctueux qui nourrit et adoucit pour une peau velours.", price:25.9, accent:"#7A4A1E", image:"/images/products/beurre-karite.png", rating:4.8, reviewCount:119, ingredients:["Beurre de Karité","Huile de Baobab"] },
  { id:12, slug:"noeuds-coco-karite-jojoba", name:"Nœuds Coco Karité & Jojoba", category:"Corps", categorySlug:"corps", concern:"Mains nourries et protégées", description:"Soin doux pour mains crépues.", price:19.9, accent:"#7A4A1E", image:"/images/products/noeux-de-coco.png", rating:4.7, reviewCount:74, ingredients:["Karité","Coco","Jojoba","Vitamine E"] },
  { id:13, slug:"apres-soleil-soothing-glow", name:"Après-Soleil Soothing Glow", category:"Corps", categorySlug:"corps", concern:"Apaisement et prolongation du bronzage", description:"Apaise, répare et prolonge le bronzage.", price:23.9, accent:"#C9825D", image:"/images/products/apres-soleil-soothing.png", rating:4.6, reviewCount:58, ingredients:["Aloe Vera","Karité","Panthénol"] },
  { id:14, slug:"fond-de-teint-melanin-match", name:"Fond de Teint Mélanin Match", category:"Maquillage", categorySlug:"maquillage", concern:"Couvrance naturelle pour teintes profondes", description:"Fond de teint fondant adapté aux carnations profondes.", price:36.9, accent:"#7A4A1E", image:"/images/products/fond-de-teint-melanin.png", badge:"Nouveau", rating:4.7, reviewCount:88, ingredients:["Vitamine E","Jojoba"] },
  { id:15, slug:"highlighter-or-noir", name:"Highlighter Or Noir", category:"Maquillage", categorySlug:"maquillage", concern:"Éclat intense pour peaux foncées", description:"Highlighter liquide au fini lumineux naturel.", price:29.9, accent:"#A87832", image:"/images/products/highliter-or-noir.png", badge:"Exclusif", rating:4.9, reviewCount:102, ingredients:["Huile de Moringa","Pigments nacrés","Vitamine E"] },
  { id:16, slug:"baume-levres-cacao-miel", name:"Baume Lèvres Cacao & Miel", category:"Maquillage", categorySlug:"maquillage", concern:"Lèvres hydratées et protégées", description:"Baume gourmand Cacao, Miel et Jojoba.", price:14.9, accent:"#7A2433", image:"/images/products/beaume-levres-cacao.png", rating:4.8, reviewCount:165, ingredients:["Beurre de Cacao","Miel","Jojoba","Vitamine E"] },
  { id:17, slug:"masque-capillaire-banane-ai", name:"Masque Capillaire Banane & Aï", category:"Cheveux", categorySlug:"cheveux", concern:"Nutrition et réparation capillaire", description:"Nourrit, répare et stimule la pousse.", price:28.9, accent:"#C9825D", image:"/images/products/masque-capillaire-banane.png", rating:4.7, reviewCount:93, ingredients:["Banane","Huile d'Aï","Karité","Protéines de Blé"] },
  { id:18, slug:"masque-capillaire-baobab-keratine", name:"Masque Capillaire Baobab & Kératine", category:"Cheveux", categorySlug:"cheveux", concern:"Définition des boucles", description:"Répare et définit les boucles. Baobab + Kératine Végétale.", price:30.9, accent:"#7A4A1E", image:"/images/products/masque-capillaire-baobab.png", badge:"Best-seller", rating:4.8, reviewCount:127, ingredients:["Baobab","Kératine Végétale"] },
  { id:19, slug:"huile-scalp-croissance", name:"Huile Scalp & Croissance", category:"Cheveux", categorySlug:"cheveux", concern:"Stimulation de la pousse", description:"Active la pousse et nourrit le cuir chevelu.", price:26.9, accent:"#3f5a2a", image:"/images/products/huile-scape-croissance.png", badge:"Nouveau", rating:4.6, reviewCount:71, ingredients:["Romarin","Ricin","Moutarde","Fenugrec"] },
  { id:20, slug:"collagene-glow-melanin", name:"Collagène Glow Melanin", category:"Compléments", categorySlug:"complements", concern:"Élasticité et éclat", description:"Soutient l'élasticité et booste l'éclat de l'intérieur. 90 gélules.", price:44.9, accent:"#A87832", image:"/images/products/collagene-glow-melanin.png", badge:"Nouveau", rating:4.7, reviewCount:62, ingredients:["Collagène Marin","Acide Hyaluronique","Vitamine C","Zinc","Biotine"] },
  { id:21, slug:"glow-inside-complexe-beaute", name:"Glow Inside Complexe Beauté", category:"Compléments", categorySlug:"complements", concern:"Éclat naturel de l'intérieur", description:"Complexe vitamines, minéraux et antioxydants. 60 gélules.", price:39.9, accent:"#A87832", image:"/images/products/glow-inside-complexe.png", rating:4.6, reviewCount:48, ingredients:["Vitamines A,C,E","Minéraux","Antioxydants"] },
  { id:22, slug:"melanin-shield-anti-oxydant", name:"Mélanin Shield Anti-oxydant", category:"Compléments", categorySlug:"complements", concern:"Protection UV et anti-pollution", description:"Protège la peau de l'intérieur. Astaxanthine + Curcuma. 60 gélules.", price:42.9, accent:"#C9825D", image:"/images/products/melanin-shield-anti-oxydant.png", badge:"Exclusif", rating:4.7, reviewCount:39, ingredients:["Astaxanthine","Curcuma","Sélénium","Vitamine E"] },
  { id:23, slug:"routine-anti-imperfections", name:"Routine Anti-Imperfections", category:"Acné & imperfections", categorySlug:"acne-imperfections", concern:"Boutons et marques post-acné", description:"Duo Gel Nettoyant + Crème Anti-Imperfections.", price:59.9, accent:"#3f5a2a", image:"/images/products/duo-routine-anti-imperfections.png", badge:"Duo", rating:4.5, reviewCount:73, ingredients:["Acide salicylique","Niacinamide","Zinc PCA"] },
  { id:24, slug:"soin-pilosite-douceur-visage", name:"Soin Douceur Pilosité Visage", category:"Pilosité faciale", categorySlug:"pilosite", concern:"Poils incarnés et irritations", description:"Apaise, hydrate et prévient les poils incarnés.", price:31.9, accent:"#A87832", image:"/images/products/exclisif-soin-douceur-pilosite.png", badge:"Exclusif", rating:4.6, reviewCount:44, ingredients:["Acide glycolique","Centella asiatica","Aloe vera"] },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("✅ Connecté à MongoDB");

  await Product.deleteMany({});
  console.log("🗑  Produits existants supprimés");

  const inserted = await Product.insertMany(products.map(({ id, ...p }) => p));
  console.log(`✅ ${inserted.length} produits insérés`);

  await mongoose.disconnect();
  console.log("✅ Seed terminé !");
}

seed().catch(console.error);
